// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: payeet.proto

package payeet

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StatusResponseCode int32

const (
	StatusResponse_SUCCESS         StatusResponseCode = 0
	StatusResponse_WORNG_CREDS     StatusResponseCode = 1
	StatusResponse_INVALID_MAIL    StatusResponseCode = 2
	StatusResponse_INVALID_SESSION StatusResponseCode = 3
)

var StatusResponseCode_name = map[int32]string{
	0: "SUCCESS",
	1: "WORNG_CREDS",
	2: "INVALID_MAIL",
	3: "INVALID_SESSION",
}

var StatusResponseCode_value = map[string]int32{
	"SUCCESS":         0,
	"WORNG_CREDS":     1,
	"INVALID_MAIL":    2,
	"INVALID_SESSION": 3,
}

func (x StatusResponseCode) String() string {
	return proto.EnumName(StatusResponseCode_name, int32(x))
}

func (StatusResponseCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{4, 0}
}

type LoginRequest_S struct {
	Session              string   `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest_S) Reset()         { *m = LoginRequest_S{} }
func (m *LoginRequest_S) String() string { return proto.CompactTextString(m) }
func (*LoginRequest_S) ProtoMessage()    {}
func (*LoginRequest_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{0}
}
func (m *LoginRequest_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest_S.Unmarshal(m, b)
}
func (m *LoginRequest_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest_S.Marshal(b, m, deterministic)
}
func (m *LoginRequest_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest_S.Merge(m, src)
}
func (m *LoginRequest_S) XXX_Size() int {
	return xxx_messageInfo_LoginRequest_S.Size(m)
}
func (m *LoginRequest_S) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest_S.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest_S proto.InternalMessageInfo

func (m *LoginRequest_S) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type LoginRequest struct {
	Mail                 string   `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{1}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Session              string   `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	User_ID              string   `protobuf:"bytes,4,opt,name=user_ID,json=userID,proto3" json:"user_ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{2}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LoginResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *LoginResponse) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *LoginResponse) GetUser_ID() string {
	if m != nil {
		return m.User_ID
	}
	return ""
}

type RegisterRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Mail                 string   `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{3}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type StatusResponse struct {
	StatusCode           StatusResponseCode `protobuf:"varint,1,opt,name=StatusCode,proto3,enum=payeet.StatusResponseCode" json:"StatusCode,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{4}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatusCode() StatusResponseCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusResponse_SUCCESS
}

func (m *StatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BalanceRequest struct {
	User_ID              string   `protobuf:"bytes,1,opt,name=user_ID,json=userID,proto3" json:"user_ID,omitempty"`
	Session              string   `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{5}
}
func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetUser_ID() string {
	if m != nil {
		return m.User_ID
	}
	return ""
}

func (m *BalanceRequest) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type BalanceResponse struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{6}
}
func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type TransferRequest struct {
	ReceiverMail         string   `protobuf:"bytes,1,opt,name=receiverMail,proto3" json:"receiverMail,omitempty"`
	SenderID             string   `protobuf:"bytes,2,opt,name=senderID,proto3" json:"senderID,omitempty"`
	Session              string   `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{7}
}
func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetReceiverMail() string {
	if m != nil {
		return m.ReceiverMail
	}
	return ""
}

func (m *TransferRequest) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *TransferRequest) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type HistoryRequest struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	SenderID             string   `protobuf:"bytes,2,opt,name=senderID,proto3" json:"senderID,omitempty"`
	Session              string   `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryRequest) Reset()         { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()    {}
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49889347cc5f18bf, []int{8}
}
func (m *HistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryRequest.Unmarshal(m, b)
}
func (m *HistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryRequest.Marshal(b, m, deterministic)
}
func (m *HistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryRequest.Merge(m, src)
}
func (m *HistoryRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryRequest.Size(m)
}
func (m *HistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryRequest proto.InternalMessageInfo

func (m *HistoryRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *HistoryRequest) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *HistoryRequest) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func init() {
	proto.RegisterEnum("payeet.StatusResponseCode", StatusResponseCode_name, StatusResponseCode_value)
	proto.RegisterType((*LoginRequest_S)(nil), "payeet.LoginRequest_S")
	proto.RegisterType((*LoginRequest)(nil), "payeet.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "payeet.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "payeet.RegisterRequest")
	proto.RegisterType((*StatusResponse)(nil), "payeet.StatusResponse")
	proto.RegisterType((*BalanceRequest)(nil), "payeet.BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "payeet.BalanceResponse")
	proto.RegisterType((*TransferRequest)(nil), "payeet.TransferRequest")
	proto.RegisterType((*HistoryRequest)(nil), "payeet.historyRequest")
}

func init() { proto.RegisterFile("payeet.proto", fileDescriptor_49889347cc5f18bf) }

var fileDescriptor_49889347cc5f18bf = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x69, 0x1e, 0xed, 0x6d, 0xb0, 0xad, 0xa1, 0x34, 0x56, 0x60, 0x81, 0xbc, 0x42, 0x20,
	0x65, 0x51, 0x90, 0x58, 0x54, 0x20, 0xb5, 0x4e, 0x40, 0x16, 0x69, 0x2a, 0x79, 0x78, 0x6c, 0x90,
	0xac, 0x69, 0x7c, 0x09, 0x16, 0x89, 0x27, 0xcc, 0x4c, 0x80, 0x0a, 0x3e, 0x0b, 0x89, 0xdf, 0x43,
	0xb6, 0x67, 0x12, 0x3b, 0x34, 0x9b, 0xee, 0x72, 0x8e, 0xef, 0xfb, 0x9c, 0x09, 0x74, 0x97, 0xec,
	0x1a, 0x51, 0x0d, 0x96, 0x82, 0x2b, 0x4e, 0xda, 0x25, 0xf2, 0x9f, 0x80, 0x3d, 0xe6, 0xb3, 0x34,
	0x8b, 0xf0, 0xdb, 0x0a, 0xa5, 0x8a, 0x29, 0xf1, 0xa0, 0x23, 0x51, 0xca, 0x94, 0x67, 0x9e, 0xf5,
	0xc8, 0x7a, 0x7c, 0x10, 0x19, 0xe8, 0xbf, 0x82, 0x6e, 0x35, 0x96, 0x10, 0x68, 0x2e, 0x58, 0x3a,
	0xd7, 0x61, 0xc5, 0x6f, 0xd2, 0x87, 0xfd, 0x25, 0x93, 0xf2, 0x07, 0x17, 0x89, 0xd7, 0x28, 0xf8,
	0x35, 0xf6, 0x7f, 0xc3, 0x5d, 0x9d, 0x2f, 0x97, 0x3c, 0x93, 0x48, 0x1e, 0xc2, 0xc1, 0xeb, 0x54,
	0x48, 0x35, 0x61, 0x0b, 0xd4, 0x55, 0x36, 0x44, 0x5e, 0x6a, 0xcc, 0xf4, 0x47, 0x5d, 0xca, 0xe0,
	0xea, 0x90, 0x7b, 0xb5, 0x21, 0x49, 0x0f, 0x3a, 0x2b, 0x89, 0x22, 0x0e, 0x87, 0x5e, 0xb3, 0xf8,
	0xd2, 0xce, 0x61, 0x38, 0xf4, 0x7f, 0x81, 0x13, 0xe1, 0x2c, 0x95, 0x0a, 0x85, 0x59, 0xe0, 0xf6,
	0xfd, 0xcd, 0xea, 0x7b, 0x3b, 0x56, 0x6f, 0x6e, 0xad, 0xfe, 0xc7, 0x02, 0x9b, 0x2a, 0xa6, 0x56,
	0x72, 0xbd, 0xfc, 0x29, 0x40, 0xc9, 0x04, 0x3c, 0x29, 0xbb, 0xdb, 0x27, 0x0f, 0x06, 0x5a, 0xa4,
	0x7a, 0xec, 0x60, 0xca, 0x13, 0x8c, 0x2a, 0xe1, 0xf9, 0xfe, 0x0b, 0x94, 0x92, 0xcd, 0xcc, 0x68,
	0x06, 0xfa, 0x6f, 0xa1, 0x99, 0x47, 0x93, 0x43, 0xe8, 0xd0, 0xf7, 0x41, 0x30, 0xa2, 0xd4, 0xbd,
	0x43, 0x1c, 0x38, 0xfc, 0x78, 0x19, 0x4d, 0xde, 0xc4, 0x41, 0x34, 0x1a, 0x52, 0xd7, 0x22, 0x2e,
	0x74, 0xc3, 0xc9, 0x87, 0xb3, 0x71, 0x38, 0x8c, 0x2f, 0xce, 0xc2, 0xb1, 0xdb, 0x20, 0xf7, 0xc0,
	0x31, 0x0c, 0x1d, 0x51, 0x1a, 0x5e, 0x4e, 0xdc, 0x3d, 0x3f, 0x00, 0xfb, 0x9c, 0xcd, 0x59, 0x36,
	0x45, 0x73, 0xb2, 0xca, 0x79, 0xad, 0xea, 0x79, 0xab, 0x8a, 0x34, 0xea, 0xb6, 0x79, 0x0a, 0xce,
	0xba, 0x88, 0xde, 0xdd, 0x83, 0xce, 0x55, 0x49, 0x19, 0x8f, 0x69, 0xe8, 0x7f, 0x05, 0xe7, 0x9d,
	0x60, 0x99, 0xfc, 0xbc, 0x51, 0xc9, 0x87, 0xae, 0xc0, 0x29, 0xa6, 0xdf, 0x51, 0x5c, 0x6c, 0xec,
	0x56, 0xe3, 0xf2, 0xdb, 0x4b, 0xcc, 0x92, 0x7c, 0x12, 0xa3, 0x95, 0xc1, 0xbb, 0xbd, 0xe2, 0x7f,
	0x02, 0xfb, 0x4b, 0x2a, 0x15, 0x17, 0xd7, 0xa6, 0xd7, 0x11, 0xb4, 0xd2, 0x2c, 0xc1, 0x9f, 0x45,
	0x93, 0x56, 0x54, 0x82, 0xdb, 0x55, 0x3f, 0xf9, 0xdb, 0x00, 0xfd, 0xca, 0xc8, 0x73, 0x68, 0xcd,
	0x73, 0xe7, 0x93, 0x23, 0x23, 0x70, 0xf5, 0x21, 0xf5, 0xef, 0x6f, 0xb1, 0xfa, 0x4a, 0x2f, 0xa0,
	0x5d, 0x64, 0x51, 0x72, 0x7c, 0x53, 0x5a, 0x4c, 0x77, 0x25, 0x9e, 0xc2, 0xbe, 0xd0, 0x56, 0x27,
	0x3d, 0x13, 0xb2, 0x65, 0xfe, 0xfe, 0xf1, 0xcd, 0x5e, 0x23, 0x2f, 0x01, 0x66, 0xa8, 0xb4, 0x62,
	0x9b, 0xce, 0x75, 0x1f, 0xf4, 0x7b, 0xff, 0xf1, 0x3a, 0xfd, 0x1c, 0x1c, 0xa5, 0x05, 0x34, 0x35,
	0xd6, 0xb1, 0x5b, 0xca, 0xee, 0x1a, 0xe1, 0xaa, 0x5d, 0xfc, 0x47, 0x3d, 0xfb, 0x17, 0x00, 0x00,
	0xff, 0xff, 0xaf, 0xaa, 0x65, 0x06, 0xb3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayeetClient is the client API for Payeet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayeetClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	LoginS(ctx context.Context, in *LoginRequest_S, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	TransferBalance(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type payeetClient struct {
	cc *grpc.ClientConn
}

func NewPayeetClient(cc *grpc.ClientConn) PayeetClient {
	return &payeetClient{cc}
}

func (c *payeetClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/payeet.payeet/login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeetClient) LoginS(ctx context.Context, in *LoginRequest_S, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/payeet.payeet/loginS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeetClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/payeet.payeet/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeetClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/payeet.payeet/getBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payeetClient) TransferBalance(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/payeet.payeet/transferBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayeetServer is the server API for Payeet service.
type PayeetServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	LoginS(context.Context, *LoginRequest_S) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*StatusResponse, error)
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	TransferBalance(context.Context, *TransferRequest) (*StatusResponse, error)
}

// UnimplementedPayeetServer can be embedded to have forward compatible implementations.
type UnimplementedPayeetServer struct {
}

func (*UnimplementedPayeetServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedPayeetServer) LoginS(ctx context.Context, req *LoginRequest_S) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginS not implemented")
}
func (*UnimplementedPayeetServer) Register(ctx context.Context, req *RegisterRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedPayeetServer) GetBalance(ctx context.Context, req *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedPayeetServer) TransferBalance(ctx context.Context, req *TransferRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferBalance not implemented")
}

func RegisterPayeetServer(s *grpc.Server, srv PayeetServer) {
	s.RegisterService(&_Payeet_serviceDesc, srv)
}

func _Payeet_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeetServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payeet.payeet/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeetServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payeet_LoginS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest_S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeetServer).LoginS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payeet.payeet/LoginS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeetServer).LoginS(ctx, req.(*LoginRequest_S))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payeet_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeetServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payeet.payeet/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeetServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payeet_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeetServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payeet.payeet/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeetServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payeet_TransferBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayeetServer).TransferBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payeet.payeet/TransferBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayeetServer).TransferBalance(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Payeet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payeet.payeet",
	HandlerType: (*PayeetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "login",
			Handler:    _Payeet_Login_Handler,
		},
		{
			MethodName: "loginS",
			Handler:    _Payeet_LoginS_Handler,
		},
		{
			MethodName: "register",
			Handler:    _Payeet_Register_Handler,
		},
		{
			MethodName: "getBalance",
			Handler:    _Payeet_GetBalance_Handler,
		},
		{
			MethodName: "transferBalance",
			Handler:    _Payeet_TransferBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payeet.proto",
}
